version: '3'

services:
  backend:
    build:
      context: ./src
    volumes:
    - ./src:/go/src/application
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
    - 8080:3333
    networks:
      - postgres_net

networks:
  postgres_net:
    external: true