version: '3'

services:
  backend:
    build:
      context: ./backend/src
    container_name: backend
    volumes:
      - ./backend/src:/go/src/application
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - 8080
    networks:
      - docker_net
      - postgres_net
    depends_on:
      - postgres

  nginx_server:
    build:
      context: ./nginx
    ports:
      - 80:80
    links:
      - backend
    networks:
      - docker_net

  postgres:
    image: postgres:9.6.17
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
      - postgres_common_volume:/home
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - postgres_net
    restart: on-failure

networks:
  postgres_net:
    external: true
  docker_net:
    external: false
#  docker_net:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 11.0.20.0/24

volumes:
  postgres_common_volume:
    external: true