version: '3'

services: 
    postgres:
        image: postgres:9.6.17
        volumes:
            - ./data/pgsql:/var/lib/postgresql/data
            - postgres_common_volume:/home
        ports: 
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
            - postgres_net
        restart: on-failure

networks:
    postgres_net:
        external: true

volumes:
    postgres_common_volume:
        external: true